import type { Metadata } from 'next';
import '../globals.css';
import { Toaster } from '@/components/ui/sonner';
import { HeaderHome } from '@/components/home/HomeHeader';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='bg-background'>
        <HeaderHome />
        <main>{children}</main>
        <Toaster richColors position='top-right' />
      </body>
    </html>
  );
}
