import type { Metadata } from 'next';
import '../globals.css';
import { Toaster } from '@/components/ui/sonner';
import { HeaderHome } from '@/components/home/HomeHeader';
import { createClient } from '@/lib/utils/supabase/server';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
type UserType = {
  name: string;
  email: string;
  avatar: string;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  return (
    <html lang='en'>
      <body className='bg-background'>
        <HeaderHome user={user ? { name: user.user_metadata.full_name ?? '', email: user.email ?? '', avatar: user.user_metadata.avatar_url ?? '' } : null} />
        <main>{children}</main>
        <Toaster richColors position='top-right' />
      </body>
    </html>
  );
}
