import type { Metadata } from 'next';
import '../../globals.css';
import { createClient } from '@/lib/utils/supabase/server';
import { redirect } from 'next/navigation';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (user) {
    return redirect('/dashboard');
  }
  return (
    <html lang='en'>
      <body className='bg-background'>
        <div className=''>{children}</div>
        <Toaster richColors position='top-right' />
      </body>
    </html>
  );
}
