import { AppSidebar } from '@/components/dashboard/app-sidebar';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import type { Metadata } from 'next';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

import { Toaster } from '@/components/ui/sonner';
import DashboardHeader from '@/components/dashboard/dashboard-header';
import '../../globals.css';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import { createClient } from '@/lib/utils/supabase/server';
import { redirect } from 'next/navigation';
import { headers } from 'next/headers';
import dynamic from 'next/dynamic';



export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const { data: user } = await (await supabase).auth.getUser();

  if (!user) {
    return redirect('/auth/login');
  }

    const headerList =await headers();
  const pathname =  headerList.get("x-current-path");
console.log('Pathname in Dashboard layout: ',pathname);
  return (
    <html lang='en'>
      <body>
        <NuqsAdapter>
          <div className=''>
            <SidebarProvider className=''>
              <AppSidebar />
              <SidebarInset className='overflow-hidden'>
                {!pathname?.split("/").includes("email") && 
                <DashboardHeader />}
                {children}
              </SidebarInset>
            </SidebarProvider>
            <Toaster richColors position='top-right' />
          </div>
          <Toaster richColors position='top-right' />
        </NuqsAdapter>
      </body>
    </html>
  );
}
