import { AppSidebar } from '@/components/dashboard/app-sidebar';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import type { Metadata } from 'next';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

import { Toaster } from '@/components/ui/sonner';
import DashboardHeader from '@/components/dashboard/dashboard-header';
import '../globals.css';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <NuqsAdapter>
          <div className=''>
            <SidebarProvider className=''>
              <AppSidebar />

              <SidebarInset className='overflow-hidden '>
                <DashboardHeader />

                {children}
              </SidebarInset>
            </SidebarProvider>
            <Toaster richColors position='top-right' />
          </div>
          <Toaster richColors position='top-right' />
        </NuqsAdapter>
      </body>
    </html>
  );
}
